# Generated by Django 3.1.4 on 2021-07-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_field',
            field=models.URLField(default='URLInput', max_length=300),
        ),
    ]
