# Generated by Django 3.1.4 on 2021-07-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_remove_comment_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='mail@email.com', max_length=254),
        ),
    ]
