# Generated by Django 3.1.4 on 2021-07-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_post_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='SOME STRING', max_length=200, unique=True),
        ),
    ]
