# Generated by Django 3.1.4 on 2021-07-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_auto_20210718_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url_field',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
