# Generated by Django 3.1.4 on 2021-07-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_auto_20210708_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url_field',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
    ]
