# Generated by Django 3.1.4 on 2021-07-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_auto_20210703_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='TextInput', max_length=200),
        ),
    ]
