# Generated by Django 3.1.4 on 2021-07-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0007_auto_20210703_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title2',
        ),
        migrations.AddField(
            model_name='post',
            name='subheading',
            field=models.CharField(default='TextInput', max_length=100),
        ),
    ]
