# Generated by Django 3.1.4 on 2021-07-03 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0008_auto_20210703_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subheading',
        ),
    ]
