# Generated by Django 3.1.4 on 2021-07-04 08:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogpost', '0011_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='Users',
        ),
    ]
