# Generated by Django 3.1.4 on 2021-07-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0012_auto_20210704_0844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
