# Generated by Django 3.1.4 on 2021-07-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0013_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='SOME_STRING', max_length=200, unique=True),
        ),
    ]
